spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
    username: 'root'
    password: '123456'
dubbo:
  application:
    logger: slf4j
    name: SysMonitorApplication
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: tri
    port: 50051
server:
  port: 8080
